.TH OCAMLBYTEINFO 1 "July 21, 2009"
.SH NAME
ocamlbyteinfo \- dump an OCaml bytecode binary description
.SH SYNOPSIS
.B ocamlbyteinfo
.RI file
.SH DESCRIPTION
Dump information contained in OCaml bytecode binary.
.sp 2
.B ocamlbyteinfo
is able to show information regarding:
.br
.IP
CRC of implementation
.sp 2
unsafe features
.SH SEE ALSO
.BR ocamlc (1),
.BR ocamlopt (1),
.BR ocamlobjinfo (1),
.BR ocamlplugininfo (1),
.BR ocamldumpapprox (1)
.br
.SH AUTHOR
This manual page was written by Mehdi Dogguy <mehdi@dogguy.org>,
for the Debian GNU/Linux system (but may be used by others).
