.TH OCAML-SOAP 1 "October 26, 2002"
.SH NAME
ocamlobjinfo \- dump an OCaml compilation unit description
.SH SYNOPSIS
.B ocamlobjinfo
.RI file\ ...
.SH DESCRIPTION
Dump information contained in OCaml compilation units.
Currently it works on .cmi, .cmo and .cma files.
.sp 2
.B ocamlobjinfo
is able to show information regarding:
.br
.IP
module names
.sp 2
unit name
.sp 2
declared primitives
.sp 2
imported interfaces
.sp 2
md5sums of imported interfaces
.sp 2
forced custom mode
.sp 2
extra C libraries needed
.sp 2
extra C flags needed
.sp 2
use of unsafe features
.PP
depending on its invocation on .cmi, .cmo or .cma arguments.
.SH SEE ALSO
.BR ocamlc (1),
.BR ocamlopt (1)
.br
.SH AUTHOR
This manual page was written by Stefano Zacchiroli <zack@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
