.TH OCAMLDUMPAPPROX 1 "February 15, 2009"
.SH NAME
ocamldumpapprox \- dump an OCaml native compilation unit description
.SH SYNOPSIS
.B ocamldumpapprox
.RI file\ ...
.SH DESCRIPTION
Dump information contained in OCaml native compilation units.
It works on .cmx and .cmxa files.
.sp 2
.B ocamldumpapprox
is able to show information regarding:
.br
.IP
CRC of implementation
.sp 2
CRC of imported interfaces and implementations
.sp 2
implementation assumptions
.PP
depending on its invocation on .cmx or .cmxa arguments.
.SH SEE ALSO
.BR ocamlc (1),
.BR ocamlopt (1),
.BR ocamlobjinfo (1)
.br
.SH AUTHOR
This manual page was written by Stéphane Glondu <steph@glondu.net>,
for the Debian GNU/Linux system (but may be used by others).
